- name: activate nginx wildfly site
  file:
    src: /etc/nginx/sites-available/wildfly
    dest: /etc/nginx/sites-enabled/wildfly
    state: link
  notify: 'restart nginx'

- name: activate nginx wildfly-websockets site
  file:
    src: /etc/nginx/sites-available/wildfly-websockets
    path: /etc/nginx/sites-enabled/wildfly-websockets
    state: link
  notify: 'restart nginx'

- name: deactivate nginx maintenance site
  file:
    path: /etc/nginx/sites-enabled/maintenance
    state: absent
  notify: 'restart nginx'

- name: deactivate nginx teaser site
  file:
    path: /etc/nginx/sites-enabled/teaser
    state: absent
  notify: 'restart nginx'
