- name: activate nginx teaser site
  file:
    src: /etc/nginx/sites-available/teaser
    dest: /etc/nginx/sites-enabled/teaser
    state: link
  notify: 'restart nginx'

- name: deactivate nginx maintenance site
  file:
    path: /etc/nginx/sites-enabled/maintenance
    state: absent
  notify: 'restart nginx'

- name: deactivate nginx wildfly site
  file:
    path: /etc/nginx/sites-enabled/wildfly
    state: absent
  notify: 'restart nginx'

- name: deactivate nginx wildfly-websockets site
  file:
    path: /etc/nginx/sites-enabled/wildfly-websockets
    state: absent
  notify: 'restart nginx'
