- name: 'Create {{ app_root }} directory'
  file:
    path: '{{ app_root }}'
    state: directory
    mode: 0755

- name: 'Create {{ app_root }}/config directory'
  file:
    path: '{{ app_root }}/config'
    state: directory
    mode: 0755

- name: 'Create {{ app_root }}/config/nginx directory'
  file:
    path: '{{ app_root }}/config/nginx'
    state: directory
    mode: 0755

- name: 'Create {{ app_root }}/config/dywa-app directory'
  file:
    path: '{{ app_root }}/config/dywa-app'
    state: directory
    mode: 0755

- name: Generate dywa-app config
  template:
    src: 'templates/app/config/dywa-app/{{ item.src }}'
    dest: '{{ app_root }}/config/dywa-app/{{ item.dest }}'
    mode: 0754
  with_items:
    - src: standalone.xml.j2
      dest: standalone.xml

- name: 'Create {{ app_root }}/config/webapp directory'
  file:
    path: '{{ app_root }}/config/webapp'
    state: directory
    mode: 0755

- name: Generate webapp config
  template:
    src: 'templates/app/config/webapp/{{ item.src }}'
    dest: '{{ app_root }}/config/webapp/{{ item.dest }}'
    mode: 0750
  with_items:
    - src: nginx.conf.j2
      dest: nginx.conf

- name: Generate nginx config
  template:
    src: 'templates/app/config/nginx/{{ item.src }}'
    dest: '{{ app_root }}/config/nginx/{{ item.dest }}'
    mode: 0750
  with_items:
    - src: nginx.conf.j2
      dest: nginx.conf
    - src: ssl.conf.j2
      dest: ssl.conf
    - src: webapp.conf.j2
      dest: webapp.conf
    - src: dywa-app.conf.j2
      dest: dywa-app.conf

- name: 'Create {{ app_root }}/maven directory'
  file:
    path: '{{ app_root }}/maven'
    state: directory
    mode: 0755

- name: Generate maven settings
  template:
    src: templates/app/maven/settings.xml.j2
    dest: '{{ app_root }}/maven/settings.xml'
    mode: 0750

- name: 'Create {{ app_root }}/src directory'
  file:
    path: '{{ app_root }}/src'
    state: directory
    mode: 0755

- name: Generate docker-compose.yml
  template:
    src: templates/app/docker-compose.yml.j2
    dest: '{{ app_root }}/docker-compose.yml'
    mode: 0750

- name: Generate docker-compose.migrate.yml
  template:
    src: templates/app/docker-compose.migrate.yml.j2
    dest: '{{ app_root }}/docker-compose.migrate.yml'
    mode: 0750

- name: Generate Dockerfile-webapp
  template:
    src: templates/app/src/Dockerfile-webapp.j2
    dest: '{{ app_root }}/src/Dockerfile-webapp'
    mode: 0750

- name: Generate Dockerfile-dywa-app
  template:
    src: templates/app/src/Dockerfile-dywa-app.j2
    dest: '{{ app_root }}/src/Dockerfile-dywa-app'
    mode: 0750

- name: Generate start.sh
  template:
    src: templates/app/start.sh.j2
    dest: '{{ app_root }}/start.sh'
    mode: 0750

- name: Generate migrate.sh
  template:
    src: templates/app/migrate.sh.j2
    dest: '{{ app_root }}/migrate.sh'
    mode: 0750

- name: Generate build.sh
  template:
    src: templates/app/build.sh.j2
    dest: '{{ app_root }}/build.sh'
    mode: 0750

- name: Generate restart.sh
  template:
    src: templates/app/restart.sh.j2
    dest: '{{ app_root }}/restart.sh'
    mode: 0750
