---
- name: Add CertBot PPA repository
  become: true
  apt_repository:
    repo: ppa:certbot/certbot

- name: Install CertBot
  become: true
  apt:
    name: certbot
    state: present
    update_cache: yes

- name: 'Create {{ certbot_webroot }} directory'
  become: true
  file:
    path: '{{ certbot_webroot }}'
    state: directory
    mode: 0755

- name: Create initial certificate
  become: true
  command: 'certbot certonly --standalone -n --agree-tos -m {{ certbot_email }} -d {{ domain }}'
  args:
    creates: '/etc/letsencrypt/live/{{ domain }}'
  when: ci_testing is undefined

- name: Configure CertBot with cli.ini
  become: true
  template:
    src: ./templates/letsencrypt/cli.ini.j2
    dest: /etc/letsencrypt/cli.ini
    mode: 0750

- name: Create renewal-hook
  become: true
  template:
    src: ./templates/letsencrypt/renewal-hooks/deploy/reload-nginx.sh.j2
    dest: /etc/letsencrypt/renewal-hooks/deploy/reload-nginx.sh
    mode: 0750
  when: ci_testing is undefined
