---
- import_tasks: docker.yml
- import_tasks: user.yml
- import_tasks: docker_swarm.yml
- import_tasks: certbot.yml
- import_tasks: reverse_proxy.yml
- import_tasks: app/directories.yml
- import_tasks: app/configs.yml
- import_tasks: app/docker.yml
- import_tasks: app/scripts.yml
- import_tasks: cron_jobs.yml
