- name: install nginx
  apt:
    name: nginx
    update_cache: yes
    state: present

- name: install letsencrypt
  apt:
    name: letsencrypt
    state: present

- name: create letsencrypt directory
  file: name=/var/www/letsencrypt state=directory

- name: remove default nginx config
  file: name=/etc/nginx/sites-enabled/default state=absent

- name: install nginx config
  template:
    src: ./files/nginx/nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: install nginx basic_auth
  template:
    src: ./files/nginx/basic_auth.j2
    dest: /etc/nginx/basic_auth

- name: install nginx maintenance site
  template:
    src: ./files/nginx/maintenance.j2
    dest: /etc/nginx/sites-available/maintenance

- name: install nginx default site
  template:
    src: ./files/nginx/start.j2
    dest: /etc/nginx/sites-available/start

- name: activate nginx default site
  file:
    src: /etc/nginx/sites-available/start
    dest: /etc/nginx/sites-enabled/start
    state: link

- name: reload nginx to activate letsencrypt site
  become: true
  service: name=nginx state=restarted

- name: create letsencrypt certificate without alternative domains
  shell: letsencrypt certonly -n --webroot -w /var/www/letsencrypt -m {{ letsencrypt_email }} --agree-tos -d {{ domain_name }}
  args:
    creates: /etc/letsencrypt/live/{{ domain_name }}
  notify: 'restart nginx'
  when: alternative_domain_name is undefined

- name: create letsencrypt certificate with alternative domains
  shell: letsencrypt certonly -n --webroot -w /var/www/letsencrypt -m {{ letsencrypt_email }} --agree-tos -d {{ domain_name }} -d {{ alternative_domain_name }}
  args:
    creates: /etc/letsencrypt/live/{{ domain_name }}
  notify: 'restart nginx'
  when: alternative_domain_name is defined

- name: generate dhparams
  shell: openssl dhparam -out /etc/nginx/dhparams.pem 2048
  args:
    creates: /etc/nginx/dhparams.pem
  notify: 'restart nginx'

- name: install nginx wildfly site
  template:
    src: ./files/nginx/wildfly.j2
    dest: /etc/nginx/sites-available/wildfly
  notify: 'restart nginx'

- name: activate nginx wildfly site
  file:
    src: /etc/nginx/sites-available/wildfly
    dest: /etc/nginx/sites-enabled/wildfly
    state: link
  notify: 'restart nginx'

- name: install nginx wildfly-websockets site
  template:
    src: ./files/nginx/wildfly-websockets.j2
    dest: /etc/nginx/sites-available/wildfly-websockets
  notify: 'restart nginx'

- name: activate nginx wildfly-websockets site
  file:
    src: /etc/nginx/sites-available/wildfly-websockets
    dest: /etc/nginx/sites-enabled/wildfly-websockets
    state: link
  notify: 'restart nginx'

- name: install nginx teaser site
  template:
    src: ./files/nginx/teaser.j2
    dest: /etc/nginx/sites-available/teaser
  notify: 'restart nginx'

- name: install nginx maintenance site
  template:
    src: ./files/nginx/maintenance.j2
    dest: /etc/nginx/sites-available/maintenance
  notify: 'restart nginx'

- name: create maintenance folder
  file:
    path: /var/www/html/maintenance
    state: directory
    mode: 0755

- name: create teaser folder
  file:
    path: /var/www/html/teaser
    state: directory
    mode: 0755

#- name: Add letsencrypt cronjob for cert renewal
#  cron:
#    name: letsencrypt_renewal
#    special_time: weekly
#    job: letsencrypt --renew certonly -n --webroot -w /var/www/letsencrypt -m {{ letsencrypt_email }} --agree-tos -d {{ domain_name }} && service nginx reload