# install
- name: install nginx
  apt:
    name: nginx=1.10.3-0ubuntu0.16.04.2
    update_cache: yes
    state: present

- name: install letsencrypt
  apt:
    name: letsencrypt
    state: present

# directories and files
- name: create letsencrypt directory
  file:
    path: /var/www/letsencrypt
    state: directory

- name: create maintenance folder
  file:
    group: '{{deployment_user}}'
    mode: 0755
    owner: '{{deployment_user}}'
    path: /var/www/html/maintenance
    state: directory

- name: check if maintenance index exists
  stat:
    path: /var/www/html/maintenance/index.html
  register: maintenance_index

- name: copy maintenance file
  copy:
    src: ./files/nginx/html/maintenance.html
    dest: /var/www/html/maintenance/index.html
    mode: 0644
  when: maintenance_index.stat.exists == False

- name: create teaser folder
  file:
    group: '{{deployment_user}}'
    mode: 0755
    owner: '{{deployment_user}}'
    path: /var/www/html/teaser
    state: directory

- name: check if teaser index exists
  stat:
    path: /var/www/html/teaser/index.html
  register: teaser_index

- name: copy teaser file
  copy:
    src: ./files/nginx/html/teaser.html
    dest: /var/www/html/teaser/index.html
    mode: 0644
  when: teaser_index.stat.exists == False

- name: create error folder
  file:
    group: '{{deployment_user}}'
    mode: 0755
    owner: '{{deployment_user}}'
    path: /var/www/html/error
    state: directory

- name: copy 502.txt file
  copy:
    src: ./files/nginx/error/502.txt
    dest: /var/www/html/error/502.txt
    mode: 0644

# install basic configs
- name: deinstall nginx default site
  file:
    name: /etc/nginx/sites-enabled/default
    state: absent
  notify: 'restart nginx'

- name: remove nginx default site
  file:
    name: /etc/nginx/sites-available/default
    state: absent
  notify: 'restart nginx'

- name: install nginx config
  template:
    src: ./files/nginx/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: 'restart nginx'

- name: install nginx basic_auth
  template:
    src: ./files/nginx/basic_auth.j2
    dest: /etc/nginx/basic_auth

- name: install nginx start site
  template:
    src: ./files/nginx/start.j2
    dest: /etc/nginx/sites-available/start
  notify: 'restart nginx'

- name: activate nginx start site
  file:
    src: /etc/nginx/sites-available/start
    dest: /etc/nginx/sites-enabled/start
    state: link
  notify: 'restart nginx'

# create letsencrypt certificate
- meta: flush_handlers

- name: Define letsencrypt command
  set_fact:
    letsencrpyt_command: 'letsencrypt certonly -n --webroot -w /var/www/letsencrypt -m {{ letsencrypt_email }} --agree-tos -d {{ domain_name }}'

- name: Create letsencrypt certificate
  shell: '{{letsencrpyt_command}}'
  args:
    creates: /etc/letsencrypt/live/{{ domain_name }}
  notify: 'restart nginx'

- name: Add letsencrypt cronjob for cert renewal
  cron:
    name: letsencrypt_renewal
    special_time: weekly
    job: '{{letsencrpyt_command}}'

- name: generate dhparams
  shell: openssl dhparam -out /etc/nginx/dhparams.pem 2048
  args:
    creates: /etc/nginx/dhparams.pem
  notify: 'restart nginx'

# install nginx sites
- name: install nginx wildfly site
  template:
    src: ./files/nginx/wildfly.j2
    dest: /etc/nginx/sites-available/wildfly
  notify: 'restart nginx'

- name: install nginx wildfly-websockets site
  template:
    src: ./files/nginx/wildfly-websockets.j2
    dest: /etc/nginx/sites-available/wildfly-websockets
  notify: 'restart nginx'

- name: install nginx teaser site
  template:
    src: ./files/nginx/teaser.j2
    dest: /etc/nginx/sites-available/teaser
  notify: 'restart nginx'

- name: install nginx maintenance site
  template:
    src: ./files/nginx/maintenance.j2
    dest: /etc/nginx/sites-available/maintenance
  notify: 'restart nginx'

# activate nginx sites
- include_tasks: 'nginx/{{ mode }}.yml'
