---

- name: 'Create deploy user ({{ deploy_user }})'
  become: true
  user:
    append: true
    create_home: true
    groups: docker
    name: '{{ deploy_user }}'
    state: present

- name: 'Create authorized keys for user ({{ deploy_user }})'
  authorized_key:
    user: '{{ deploy_user }}'
    state: present
    key: '{{ item }}'
  with_items: '{{ deploy_user_authorized_keys }}'
