- name: add group wildfly
  group:
    name: wildfly
    state: present

- name: add user wildfly
  user:
    name: wildfly
    group: wildfly
    shell: /sbin/nologin
    state: present

- name: install the package openjdk-8-jdk
  apt:
    name: openjdk-8-jdk
    update_cache: yes
    state: present

- name: install the package maven
  apt:
    name: maven
    update_cache: yes
    state: present

- name: 'check if {{wildfly_home}} is present'
  stat: path='{{wildfly_home}}'
  register: wildfly_home_stat_result

- name: download wildfly
  get_url:
    url: 'https://download.jboss.org/wildfly/{{wildfly_version}}/wildfly-{{wildfly_version}}.tar.gz'
    dest: '{{wildfly_download_path}}'
    checksum: md5:85caaab6ff0e729a9a92d49ddfb7d162
  when: wildfly_home_stat_result.stat.exists == False

- name: unarchive wildfly
  unarchive:
    src: '{{wildfly_download_path}}'
    dest: '/opt'
    creates: '{{wildfly_home}}'
    remote_src: True
  when: wildfly_home_stat_result.stat.exists == False

- name: create postgresql driver folder
  file:
    path: '{{postgresql_folder}}'
    state: directory
    mode: 0755

- name: install postgresql driver
  get_url:
    url: https://jdbc.postgresql.org/download/postgresql-42.2.5.jar
    dest: '{{postgresql_folder}}'
    checksum: md5:47d66d83f9894ebbb18df20d9ad2e5d3

- name: copy postgresql driver module.xml
  copy:
    src: ./files/wildfly/postgresql-module.xml
    dest: '{{postgresql_module_file}}'

- name: copy standalone.xml
  template:
    src: ./files/wildfly/standalone.xml.j2
    dest: '{{wildfly_standalone_configuration_path}}'
    force: yes
  notify: 'wildfly config changed'

- name: copy standalone.conf
  template:
    src: ./files/wildfly/standalone.conf
    dest: '{{wildfly_bin_path}}'
    force: yes
  notify: 'wildfly config changed'

- name: 'set ownership of {{wildfly_home}}'
  file:
    path: '{{wildfly_home}}'
    owner: wildfly
    group: wildfly
    recurse: yes

- name: 'create and set mode of {{wildfly_data_files_path}}'
  file:
    group: wildfly
    mode: 'u=rwX,g=rwX,o='
    owner: wildfly
    path: '{{wildfly_data_files_path}}'
    recurse: yes
    state: directory

- name: 'set mode of {{wildfly_deployments_path}}'
  file:
    group: wildfly
    mode: 'u=rwX,g=rwX,o='
    owner: wildfly
    path: '{{wildfly_deployments_path}}'
    recurse: yes

- name: 'set mode of {{wildfly_logs_path}}'
  file:
    group: wildfly
    mode: 'u=rwX,g=rwX,o='
    owner: wildfly
    path: '{{wildfly_logs_path}}'
    recurse: yes

- name: install wildfly.service file
  template:
    src: ./files/wildfly/wildfly.service.j2
    dest: /etc/systemd/system/wildfly.service
  notify: 'wildfly post install'

- name: install wildfly environment file
  template:
    src: ./files/wildfly/wildfly.j2
    dest: /etc/default/wildfly
  notify: 'wildfly post install'

- meta: flush_handlers
