- name: Generate restic repository password
  template:
    src: 'templates/app/config/backup/restic-repository-password.j2'
    dest: '{{ app_root }}/config/backup/restic-repository-password'
    mode: 0600
  when: backup_enabled == true or restore_enabled == true

- name: Copy private key for backup user
  copy:
    src: '{{ playbook_dir }}/{{ backup_user_id_rsa_path }}'
    dest: '{{ app_root }}/config/backup/id_rsa'
    mode: 0600
  when: backup_enabled == true or restore_enabled == true

- name: Generate ssh_config for backup
  template:
    src: 'templates/app/config/backup/ssh_config.j2'
    dest: '{{ app_root }}/config/backup/ssh_config'
    mode: 0644
  when: backup_enabled == true or restore_enabled == true

- name: Generate dywa-app config
  template:
    src: 'templates/app/config/dywa-app/{{ item.src }}'
    dest: '{{ app_root }}/config/dywa-app/{{ item.dest }}'
    mode: 0644
  with_items:
    - src: standalone.xml.j2
      dest: standalone.xml
    - src: standalone.conf.j2
      dest: standalone.conf

- name: Generate nginx webapp config
  template:
    src: 'templates/app/config/webapp/{{ item.src }}'
    dest: '{{ app_root }}/config/webapp/{{ item.dest }}'
    mode: 0644
  with_items:
    - src: nginx.conf.j2
      dest: nginx.conf

- name: Generate nginx proxy config
  become: true
  template:
    src: 'templates/app/config/nginx/{{ item.src }}'
    dest: '/etc/nginx/{{ item.dest }}'
    mode: 0644
  with_items:
    - src: nginx.conf.j2
      dest: nginx.conf
  notify:
    - restart nginx

- name: Generate nginx proxy app config
  become: true
  template:
    src: 'templates/app/config/nginx/conf.d/{{ item.src }}'
    dest: '/etc/nginx/conf.d/{{ item.dest }}'
    mode: 0644
  with_items:
    - src: app.conf.j2
      dest: app.conf
  notify:
    - restart nginx

- name: Generate nginx proxy ssl config
  become: true
  template:
    src: 'templates/app/config/nginx/conf.d/{{ item.src }}'
    dest: '/etc/nginx/conf.d/{{ item.dest }}'
    mode: 0644
  with_items:
    - src: ssl.conf.j2
      dest: ssl.conf
  notify:
    - restart nginx
  when: https

- name: Generate nginx proxy services file
  become: true
  template:
    src: 'templates/app/config/nginx/conf.d/services.conf.j2'
    dest: '/etc/nginx/conf.d/services.conf'
    mode: 0644
  notify:
    - restart nginx
  when: services|length > 0

- name: Delete old nginx config files
  become: true
  file:
    state: absent
    path: '/etc/nginx/conf.d/{{ item }}'
  with_items:
    - webapp.conf
    - dywa-app.conf

- name: Install packages for generating htpasswd files
  become: true
  apt:
    name: ['python3-passlib']
    state: present
    update_cache: yes

- name: Generate nginx htpasswd-dywa file
  become: true
  htpasswd:
    dest: '/etc/nginx/htpasswd-dywa'
    name: '{{ dywa_http_auth_username }}'
    password: '{{ dywa_http_auth_password }}'
    mode: 0644
  notify:
    - restart nginx

- name: Generate nginx htpasswd-mailcatcher file
  become: true
  htpasswd:
    dest: '/etc/nginx/htpasswd-mailcatcher'
    name: '{{ mailcatcher_http_auth_username }}'
    password: '{{ mailcatcher_http_auth_password }}'
    mode: 0644
  when: deployment_tier != 'production'
  notify:
    - restart nginx

- name: Generate maven settings
  template:
    src: templates/app/maven/settings.xml.j2
    dest: '{{ app_root }}/maven/settings.xml'
    mode: 0644
