- name: Generate dywa-app config
  template:
    src: 'templates/app/config/dywa-app/{{ item.src }}'
    dest: '{{ app_root }}/config/dywa-app/{{ item.dest }}'
    mode: 0754
  with_items:
    - src: standalone.xml.j2
      dest: standalone.xml

- name: Generate nginx webapp config
  template:
    src: 'templates/app/config/webapp/{{ item.src }}'
    dest: '{{ app_root }}/config/webapp/{{ item.dest }}'
    mode: 0750
  with_items:
    - src: nginx.conf.j2
      dest: nginx.conf

- name: Generate nginx proxy config
  template:
    src: 'templates/app/config/nginx/{{ item.src }}'
    dest: '{{ app_root }}/config/nginx/{{ item.dest }}'
    mode: 0750
  with_items:
    - src: nginx.conf.j2
      dest: nginx.conf

- name: Generate nginx proxy conf.d files
  template:
    src: 'templates/app/config/nginx/conf.d/{{ item.src }}'
    dest: '{{ app_root }}/config/nginx/conf.d/{{ item.dest }}'
    mode: 0750
  with_items:
    - src: ssl.conf.j2
      dest: ssl.conf
    - src: webapp.conf.j2
      dest: webapp.conf
    - src: dywa-app.conf.j2
      dest: dywa-app.conf

- name: Install packages for generating htpasswd files
  become: true
  apt:
    name: ['python3-passlib']
    state: present
    update_cache: yes

- name: Generate nginx htpasswd file
  htpasswd:
    dest: '{{ app_root }}/config/nginx/htpasswd'
    name: '{{ dywa_http_auth_username }}'
    password: '{{ dywa_http_auth_password }}'
    mode: 0754

- name: Generate maven settings
  template:
    src: templates/app/maven/settings.xml.j2
    dest: '{{ app_root }}/maven/settings.xml'
    mode: 0750
