- name: Generate docker-compose.yml
  template:
    src: templates/app/docker-compose.yml.j2
    dest: '{{ app_root }}/docker-compose.yml'
    mode: 0750

- name: Generate Dockerfile-webapp
  template:
    src: templates/app/src/Dockerfile-webapp.j2
    dest: '{{ app_root }}/src/Dockerfile-webapp'
    mode: 0750

- name: Generate Dockerfile-dywa-app
  template:
    src: templates/app/src/Dockerfile-dywa-app.j2
    dest: '{{ app_root }}/src/Dockerfile-dywa-app'
    mode: 0750

- name: Generate Dockerfile-maintenance-page
  template:
    src: templates/app/src/Dockerfile-maintenance-page.j2
    dest: '{{ app_root }}/src/Dockerfile-maintenance-page'
    mode: 0750

- name: Generate robots.txt
  template:
    src: templates/app/src/robots.txt.j2
    dest: '{{ app_root }}/src/robots.txt'
    mode: 0754
  when: deployment_tier != 'production'

