- name: Generate app
  template:
    src: templates/app/app.py
    dest: '{{ app_root }}/app'
    mode: 0750

- name: Generate app completion
  template:
    src: templates/app/bash_completion
    dest: '{{ user_home }}/.bash_completion'
    mode: 0750
