FROM google/dart:2.4 as dart
RUN pub global activate webdev
WORKDIR /app
COPY ./webapp/pubspec.* /app/
RUN pub get
COPY ./webapp /app
RUN /root/.pub-cache/bin/webdev build

FROM nginx:{{ nginx_version }}
COPY --from=dart /app/build /usr/share/nginx/html
{% if deployment_tier != 'production' %}
COPY ./robots.txt /usr/share/nginx/html/
{% endif %}
